### PR TITLE
Stop releasing snapshots to Maven

### PR DESCRIPTION
**Pull request by milanvdm**
Closes https://github.com/typelevel/munit-cats-effect/issues/131

### CODE REVIEW

**Comment by mpilquist** [comment]
Curious for the motivation on this one?

**Comment by milanvdm** [comment]
@mpilquist In the issue, a user wants to create a giter8 template and the snapshots were blocking him to correctly use the latest version.
I don't have a strong opinion on this tbh :)

**Comment by mpilquist** [comment]
Paging @djspiewak

**Comment by mpilquist** [comment]
I paged you b/c I think we should be using real snapshots for CI builds.

**Comment by djspiewak** [comment]
I think real snapshots are almost useless. The instability means that they can't be used at all in a transitive context, and can only be used directly when paired with a pinky promise not to overwrite. Given that we have a very deep ecosystem, that kind of trade off seems bad.

Conversely, hash snapshots form a composable foundation for a lot of tooling, some of which we haven't even built yet. For example, an ecosystem sort of community build is doable on that foundation. The only cost is they clutter the repository search tools.

**Comment by armanbilge** [comment]
FWIW, I _really_ appreciate snapshots. fs2's reliable snapshots have been invaluable time and time again.

> I paged you b/c I think we should be using real snapshots for CI builds.

💯 to this. Actually, this is what I was trying to support with my PR that broke sbt-spiewak.

> I find snapshots are generally even more convenient when you cut them off of PRs, which is a manual process even when this setting is true

That's fair. But, even after a PR is merged snapshots can still be useful. For example, we still have a lot of open questions regarding JS tracing even though it's merged. If CE released snapshots it would make it so much easier for downstreams to start playing with this and hopefully provide some useful feedback before 3.3.

> and can only be used directly when paired with a pinky promise not to overwrite.

AFAICT as long as you are using git-based versioning it is _very_ hard to overwrite a snapshot with different code. Putting aside malicious/bad actors (but then again, snapshots aren't signed anyway right?). Also ... can't we still have snapshots _and_ stable "snapshots"? These aren't mutually exclusive. IMO the pinky promise here is we are trusting that _downstreams_  don't use snapshots where they really want something stable.

**Comment by armanbilge** [comment]
We can close this as of https://github.com/typelevel/munit-cats-effect/pull/182.

**Pull request closed without merging**
