### PR TITLE
Migrate to sbt-typelevel

### PR DESCRIPTION
**Pull request by armanbilge**
Fixes https://github.com/typelevel/munit-cats-effect/issues/131. Supersedes https://github.com/typelevel/munit-cats-effect/pull/135.

MiMa is currently disabled, is this intentional?

### CODE REVIEW

**Comment by danicheg** [comment]
> MiMa is currently disabled, is this intentional?

It isn't desirable, even if it was intentional, I opine.

**Comment by armanbilge** [comment]
> It isn't desirable, even if it was intentional, I opine.

Agree :) you should remove the following settings then. I propose you do that in a follow-up PR, because there may be many MiMa problems to investigate since it was not being checked.

https://github.com/typelevel/munit-cats-effect/blob/99edcb8366984b892a83866e6cf69e9ac8207a3a/build.sbt#L24

https://github.com/typelevel/munit-cats-effect/blob/99edcb8366984b892a83866e6cf69e9ac8207a3a/build.sbt#L48

**Comment by danicheg** [comment]
I agree that `MiMa` enabling isn't a topic of current PR. Though it's good to get what others think about it.

**Comment by armanbilge** [comment]
We just got conflicts :( any hope to merge this?

**Review by danicheg — APPROVED** [review]
I think this PR had waited for review pretty long and anybody who wanted to check it could do it. In my judgment, I don't see any blockers to don't merge that. Thanks, @armanbilge!

**Pull request merged**
