### PR TITLE
Add `assertIO` method to simplify asserting `IO`s

### PR DESCRIPTION
**Pull request by alejandrohdezma**
## Motivation

There are some cases when returning an IO can be not-very readable and can pollute the code with lots of `.flatMap(a => IO(assertEquals(a, "bla bla"))`. So it would be ideal to have a method to do this in a more readable way.

## What has been done in this PR?

Add an `assertIO` method that can be used in cases like this:

```scala
//before
myIO.flatMap(value => assertEquals(value, myExpectedValue))

//after
assertIO(myIO, returns = myExpectedValue)
```

**Update 18th Oct, 2020**

More assertions have been added:

- `interceptIO`, for intercepting a `Throwable` being thrown inside the provided `IO`:
```scala
val io = IO.raiseError[Unit](MyException("BOOM!"))

interceptIO[MyException](io)
```
- `interceptMessageIO`, for intercepting a `Throwable` with a certain message being thrown inside the provided `IO`:

```scala
val io = IO.raiseError[Unit](MyException("BOOM!"))

interceptIO[MyException]("BOOM!")(io)
```
- Also `*SyncIO` versions of all the previous assertions have been added.
- In addition, syntax version of all the assertions have been added (similar to Specs2/Scalatest DSL):

```scala
io assertEquals 2
io.intercept[IllegalArgumentException]
```

### CODE REVIEW

**Comment by mpilquist** [comment]
Thanks, this is definitely interesting. Some miscellaneous thoughts:
- Should we add methods like this as syntax, [like is done in fs2](https://github.com/typelevel/fs2/blob/main/core/shared/src/test/scala/fs2/Fs2Suite.scala#L50-L74)?
- Should we align naming to allow for additional methods to get added over time -- e.g. `myIO.assertEquals(b)`
- Should we support an arbitrary `F[_]` instead of only `IO`?

**Comment by alejandrohdezma** [comment]
> * Should we add methods like this as syntax, [like is done in fs2](https://github.com/typelevel/fs2/blob/main/core/shared/src/test/scala/fs2/Fs2Suite.scala?rgh-link-date=2020-09-30T15%3A45%3A24Z#L50-L74)?
> * Should we align naming to allow for additional methods to get added over time -- e.g. `myIO.assertEquals(b)`

That was my initial thought (adding it as syntax to `IO`), but since all the assertions in MUnit are meant to be used as `assertBlaBla(obtained, expected)` I decided to follow that pattern (and that's why I called it `assertIO`, instead of `assertEquals`). However, despite all that I don't mind making the change to syntax if you think it makes more sense :)

> * Should we support an arbitrary `F[_]` instead of only `IO`?

I also thought about this, but since mostly everyone uses `IO` for their tests (and the suite itself works with `IO`) I decided to go with it. Do you think there are use-cases for other `F`s in this suite?

**Comment by alejandrohdezma** [comment]
Hey @mpilquist did you have time to take a look at this? Thanks!

**Comment by mpilquist** [comment]
Apologies on the delay on this one. I was hoping to hear from some more folks before merging.


> That was my initial thought (adding it as syntax to IO), but since all the assertions in MUnit are meant to be used as assertBlaBla(obtained, expected) I decided to follow that pattern (and that's why I called it assertIO, instead of assertEquals). However, despite all that I don't mind making the change to syntax if you think it makes more sense :)

We'll likely need effectful versions of others like `assertThrows` and maybe `assert`. We could go with `assertEqualsF`, `assertThrowsF`, etc., but I prefer the syntax versions -- `(fa: F[A]).assertEquals(expected)`

> I also thought about this, but since mostly everyone uses IO for their tests (and the suite itself works with IO) I decided to go with it. Do you think there are use-cases for other Fs in this suite?

In FS2, we have some tests in `SyncIO`, which is particularly useful when cross-building against Scala.js.

**Comment by alejandrohdezma** [comment]
Hi @mpilquist, I've added the following changes:

- `interceptIO` & `interceptMessageIO`, for catching exceptions, following [MUnit's own assertions](https://github.com/scalameta/munit/blob/eb4574c3ea7c27f9863b3f94c664b67280cc5e48/munit/shared/src/main/scala/munit/Assertions.scala#L163-L173)
- Versions of the assertions for the `SyncIO`: `assertSyncIO`, `interceptSyncIO` & `interceptMessageSyncIO`.
- Syntax version of all the previous assertions, for those that prefer them:

```scala
io assertEquals 2
```

☝🏼 I think is important to keep also the non-syntax version, as is most inlined with MUnit's own assertions (instead of ScalaTest/Specs2 infix syntax).

**Comment by mpilquist** [comment]
This looks great!

**Pull request merged**
